### PR TITLE
Fix missing apt packages

### LINKED ISSUE #7: apt packages cannot installed
When installing `./bootstrap.sh all --no-homebrew-setup` the packages cannot installed via apt.

OS: Debian 11
Arch: amd64

### PR DESCRIPTION
**Pull request by bjoerntorben**
Execute apt-get update before packages are going to be installed.

Fixes #7

### CODE REVIEW

File: bootstrap.sh [hunk 1]
```diff
@@ -400,6 +400,9 @@ setup_packages() {
         return 1
     fi
 
+    info "Update sources"
+    sudo apt-get update
```
Comment (MoonLiightz) [inline bootstrap.sh]: If we do this here at this point, the script would no longer work on Linux systems that do not use apt. Can you maybe make an `update_sources` function, call it here and then check in it like `prompt_install` the used package manager to update the sources?

**Review by MoonLiightz — CHANGES_REQUESTED** [review]

**Review by MoonLiightz — APPROVED** [review]

**Comment by MoonLiightz** [comment]
Thanks, I think we can merge this now.
